### ISSUE TITLE
Running CF modeling from the GUI and pRFandCFdata lead to different maps

### ISSUE THREAD

**Issue by ahmadi123** [nicogravel/CFmodelingTools#1]
Dear Nicolas, 
I am running CF modeling in a data set and have encountered different outputs while running it from the GUI which calls ccmMain.m and while trying pRFandCFdata. Namely, variance explained computed by ccmMain is much higher than what is computed by pRFandCFdata. It is very clear when I check the coherence view of the two ccModel generated by the above mentioned codes. I know the two codes are sort of different but the underlying prinicples of both  are the same. So, my questions are as follows:
Is the observed difference normal and which code is better to use?
The derived pRF maps of both codes are very far from the original pRF maps. I have read about this discrepancy in your resting state paper but the data I am working on are obtained from fMRI pRF-mapping. Since this is my first time running CF modeling, I am not sure whether such a discrepancy is acceptable for fMRI data as well. 
Finally, can CF modeling be performed on extensions of pRF model in which instead of one 2D Gaussian, two mirrored 2D Gaussians are used? (see here for more info: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3427398 )
Any help is greatly appreciated. 
Kind regards, 
Khazar Ahmadi

**Comment by nicogravel** [comment]
The code is meant to be used within scripts, not the GUI, sorry.  The
difference in variance explained is: you get the variance explained
corrected by the degrees of freedom of your data, voila.
The CF maps can be far from the original pRF maps for a variety of reason :
1) you are using resting state data, 2) your source ROIs have holes (not
fully mapped), are badly segmented, etc), 3) the quality (field strength,
segmentation, movement, etc) of the data is not very good, and 4) the
subject you are looking has lots of veins in the calcarine sulcus, 5) that
the method has its limitations.
To explore other models with more parameters you have to modify certain
parts of the code but beware of the burdens and advantages of a big
parameter space for the search and fit procedure. There is another strategy
to compute CF based on Ridge regression first, and model fit later.

Hope that helps,

Kind regards,

Nicolas



2017-07-28 10:56 GMT+02:00 Ahmadi Khazar <notifications@github.com>:

**Comment by ahmadi123** [comment]
Thanks a lot for the thorough answer!
Regards, 
Khazar
